### ISSUE TITLE
Strong slow down, unability to use.

### ISSUE THREAD

**Issue by AegisMaelstrom** [k-nut/wikidata-game#1]
I have returned to Wikidata Game after some weeks to realize that it has really slowed down; what is more, the particular items very often do not load at all and the issue seems to be worsening (in the beginning it was just slow and halting, now it is not usable). In result, sometimes I wait even dozens of seconds to load a person or gender single question and very often nothings loads at all.

Hint: if the load is successful pretty often a second or even third question in the game loads very promptly. After that it halts again and all I see is:
_Looking for random gender-less person data..._ with "Remembering" description where valid.

The only thing that seems to be working now (albeit quite slowly) are settings and statistics. Others load very, very rarely.

On the contrary, the distributed Wikidata Game (particular games of source metadata, geo units, kian...) seems to be working maybe slowish but fine.

The problem was tested on two different PCs, with Firefox and Microsoft Edge. "Fun" fact: Microsoft Edge got completely crashed when the question item was being loaded.

**Comment by k-nut** [comment]
It seems like you are referring to https://tools.wmflabs.org/wikidata-game/ .
This repository is not what you are looking for, it is a different project. You should report your problems here: https://bitbucket.org/magnusmanske/wikidata-game/issues?status=new&status=open
